######################################################################
# Automatically generated by qmake (3.0) Fri Oct 9 22:53:00 2015
######################################################################

QT+=opengl
QT+=widgets
TEMPLATE = app
TARGET = a2
INCLUDEPATH += .

# Input
HEADERS += a2.h algebra.h draw.h renderer.h window.h
SOURCES += a2.cpp algebra.cpp draw.cpp main.cpp renderer.cpp window.cpp

